version: '3.9'

services:
  rag_service:
    container_name: rag_container
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped
