# docker-compose.yml
services:
  rag_service:
    build: .
    # Mount your working directory into /app in the container
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    # Override the default CMD to enable hot-reload
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000